### ISSUE TITLE
Preferably keep generic, and upstream has few updates

### ISSUE THREAD

**Issue by avih** [Kagami/mpv-promise#1]
I see that you modified the source code a bit to remove the search for async function and few more. I think it would be better to keep it generic (so that it can still work in browsers, node, etc). If you have suggestion to make it better generic, then I can take PR, though generally I consider it complete.

I had few more old local patches which I didn't push to the repo, so I pushed them now (3 commits), so you probably want to sync up, though it would probably be easier if you revert your changes first, or some such.

**Comment by Kagami** [comment]
Initially I wanted to sent PR, but I didn't particularly like the CommonJS wrapper output in ES modules, however this is kinda minor.

I can make a PR with fixes if you're ok with pushing nopromise package to npm.

**Comment by avih** [comment]
> I didn't particularly like the CommonJS wrapper output in ES modules

Not sure I follow what you mean exactly. Can you post a diff (preferably to current upstream) which demonstrates what you'd change in this regard and explain why?

> I can make a PR with fixes

Sure, if it fixes real issues then do send a PR.

> if you're ok with pushing nopromise package to npm.

I won't maintain it with npm, but I think it should stay as close to upstream as possible regardless.

EDIT:
Not sure I follow, do you mean that I presonally would maintain the npm package? or whether I'm ok that you push nopromise to npm?

I'm OK if you push it (e.g. with your fork, with credit etc), but I won't maintain/push it myself to npm.

**Comment by Kagami** [comment]
Continued at https://github.com/avih/nopromise/pull/1.
